# AWS Production Docker Compose Configuration
# Note: MongoDB is deployed separately in UAT/Production environments
# The MONGODB_URI environment variable should point to your external MongoDB instance
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.backend
        environment:
            MONGODB_URI: ${MONGODB_URI}
            PORT: 5050
            NODE_ENV: production
            ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
            ADMIN_PASSWORD: ${ADMIN_PASSWORD:-password}
        ports:
            - '80:5050' # Map internal 5050 to external 80 for direct access
        restart: unless-stopped
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '3'
        volumes:
            - uploads:/app/uploads
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:5050/api/surveys']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

volumes:
    uploads:
