services:
  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: survey
    volumes:
      - mongodb_data:/data/db
    networks:
      - survey-network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/survey
      - PORT=5050
      - NODE_ENV=production
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test:
        - 'CMD-SHELL'
        - 'wget --no-verbose --tries=1 --spider http://localhost:5050/health || exit 1'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    networks:
      - survey-network
    volumes:
      - uploads:/app/uploads

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '80:80'
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - survey-network

networks:
  survey-network:
    driver: bridge

volumes:
  mongodb_data:
  uploads: